class DBM_Card_User_Data {
    static TABLENAME = "card_user_data";

    static columns = {
        id_user: "id_user", 
        level: "level",
        exp: "exp",
        daily_last: "daily_last",
        sale_token: "sale_token",
        spawn_token: "spawn_token",
        card_id_selected: "card_id_selected",
        card_avatar_form: "card_avatar_form",
        card_set_token: "card_set_token",
        status_effect: "status_effect",
        status_effect_2: "status_effect_2",
        mofucoin: "mofucoin",
        daily_quest: "daily_quest",
        special_point: "special_point",
        color: "color",
        color_level_pink: "color_level_pink",
        color_point_pink: "color_point_pink",
        color_level_blue: "color_level_blue",
        color_point_blue: "color_point_blue",
        color_level_yellow: "color_level_yellow",
        color_point_yellow: "color_point_yellow",
        color_level_purple: "color_level_purple",
        color_point_purple: "color_point_purple",
        color_level_red: "color_level_red",
        color_point_red: "color_point_red",
        color_level_green: "color_level_green",
        color_point_green: "color_point_green",
        color_level_white: "color_level_white",
        color_point_white: "color_point_white",
        series_set: "series_set",
        sp001: "sp001",
        sp002: "sp002",
        sp003: "sp003",
        sp004: "sp004",
        sp005: "sp005",
        sp006: "sp006",
        sp007: "sp007",
        sp008: "sp008",
        sp009: "sp009",
        sp010: "sp010",
        sp011: "sp011",
        sp012: "sp012",
        sp013: "sp013",
        sp014: "sp014",
        sp015: "sp015",
        newbie_reward_claim: "newbie_reward_claim",
        hp: "hp",
        created_at: "created_at",
    };
}

module.exports = DBM_Card_User_Data;